#!/usr/bin/env bash
set -euo pipefail

: "${VOLUNDR_LIVE_ENV_FILE:?VOLUNDR_LIVE_ENV_FILE is required}"
: "${VOLUNDR_LIVE_DATA_DIR:?VOLUNDR_LIVE_DATA_DIR is required}"
: "${VOLUNDR_LIVE_API_PORT:?VOLUNDR_LIVE_API_PORT is required}"

cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/../../backend" && pwd)"
. "$VOLUNDR_LIVE_ENV_FILE"
export VOLUNDR_AI_PROVIDER=gemini_api
export VOLUNDR_DEVELOPER_TOOLS_ENABLED=true
export VOLUNDR_GEMINI_API_MAX_RETRIES=1
export VOLUNDR_VALIDATED_CADQUERY_FLOW_ENABLED="${VOLUNDR_LIVE_VALIDATED_CADQUERY_FLOW_ENABLED:-false}"
export VOLUNDR_EXECUTABLE_CADQUERY_FLOW_ENABLED="${VOLUNDR_LIVE_EXECUTABLE_CADQUERY_FLOW_ENABLED:-false}"
export VOLUNDR_DATA_DIR="$VOLUNDR_LIVE_DATA_DIR/data"
export VOLUNDR_CAD_WORKSPACE_DIR="$VOLUNDR_LIVE_DATA_DIR/data/jobs"
export VOLUNDR_BUILD_GIT_SHA="${VOLUNDR_BUILD_GIT_SHA:-$(git rev-parse HEAD)}"
export VOLUNDR_BUILD_BRANCH="${VOLUNDR_BUILD_BRANCH:-$(git branch --show-current)}"
export VOLUNDR_BUILD_TIMESTAMP="${VOLUNDR_BUILD_TIMESTAMP:-$(git show -s --format=%cI HEAD)}"
export VOLUNDR_BUILD_DIRTY="${VOLUNDR_BUILD_DIRTY:-false}"
export VOLUNDR_WORKER_BUILD_GIT_SHA="${VOLUNDR_WORKER_BUILD_GIT_SHA:-$VOLUNDR_BUILD_GIT_SHA}"
export VOLUNDR_WORKER_BUILD_TIMESTAMP="${VOLUNDR_WORKER_BUILD_TIMESTAMP:-$VOLUNDR_BUILD_TIMESTAMP}"
export VOLUNDR_WORKER_BUILD_DIRTY="${VOLUNDR_WORKER_BUILD_DIRTY:-$VOLUNDR_BUILD_DIRTY}"
export PYTHONPATH=.
../backend/.venv/bin/alembic upgrade head

exec env \
  VOLUNDR_AI_PROVIDER=gemini_api \
  VOLUNDR_DEVELOPER_TOOLS_ENABLED=true \
  VOLUNDR_GEMINI_API_MAX_RETRIES=1 \
  VOLUNDR_VALIDATED_CADQUERY_FLOW_ENABLED="$VOLUNDR_LIVE_VALIDATED_CADQUERY_FLOW_ENABLED" \
  VOLUNDR_EXECUTABLE_CADQUERY_FLOW_ENABLED="$VOLUNDR_LIVE_EXECUTABLE_CADQUERY_FLOW_ENABLED" \
  VOLUNDR_DATA_DIR="$VOLUNDR_LIVE_DATA_DIR/data" \
  VOLUNDR_CAD_WORKSPACE_DIR="$VOLUNDR_LIVE_DATA_DIR/data/jobs" \
  VOLUNDR_BUILD_GIT_SHA="$VOLUNDR_BUILD_GIT_SHA" \
  VOLUNDR_BUILD_BRANCH="$VOLUNDR_BUILD_BRANCH" \
  VOLUNDR_BUILD_TIMESTAMP="$VOLUNDR_BUILD_TIMESTAMP" \
  VOLUNDR_BUILD_DIRTY="$VOLUNDR_BUILD_DIRTY" \
  VOLUNDR_WORKER_BUILD_GIT_SHA="$VOLUNDR_WORKER_BUILD_GIT_SHA" \
  VOLUNDR_WORKER_BUILD_TIMESTAMP="$VOLUNDR_WORKER_BUILD_TIMESTAMP" \
  VOLUNDR_WORKER_BUILD_DIRTY="$VOLUNDR_WORKER_BUILD_DIRTY" \
  PYTHONPATH=. \
  ../backend/.venv/bin/uvicorn app.main:app --host 127.0.0.1 --port "$VOLUNDR_LIVE_API_PORT" \
  >"$VOLUNDR_LIVE_DATA_DIR/api.log" 2>&1
